spring:
  activemq:
    broker-url: tcp://localhost:32776 # must be port 61616, but the container port is 32776 -> 61616
    user: admin
    password: admin
    packages:
      trust-all: true

application:
  jms:
    queue:
      test: test-queue
    topic:
      test: test-topic
